channels:
- defaults
- conda-forge
- bioconda
- anaconda
dependencies:
- python==3.11.9
- pip
- numpy
- dill
- matplotlib
- numpy
- pandas
- scipy
- sortedcontainers
- tensorflow-cpu==2.14.0
- keras==2.14.0
- pymzml
- spyder
- pip:
  - brain-isotopic-distribution
